language: python
python:
  - "3.4"
  # - "3.5"
  # - "3.6"
# command to install dependencies
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements.txt
  - sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0
# command to run tests
script:
  - a=1; if a==1; then echo "Hello World!"; fi
  # - pytest # or py.test for Python versions 3.5 and below
